package edu.orangecoastcollege.watchplace.view;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Slider;

import javafx.scene.control.TextArea;

public class AddWatchReview implements Initializable {
	@FXML
	private Slider rateSlider;
	@FXML
	private TextArea reviewTA;
	@FXML
	private Button addButton;
	@FXML
	private Button cancelButton;

	// Event Listener on Button[#addButton].onAction
	@FXML
	public void addReview() {
		
	}
	// Event Listener on Button[#cancelButton].onAction
	@FXML
	public void cancel() {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		
		
	}
}
