package edu.orangecoastcollege.watchplace.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import edu.orangecoastcollege.watchplace.controller.Controller;
import javafx.event.ActionEvent;

import javafx.scene.control.Slider;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.input.MouseEvent;

public class HomeScene {
	private static Controller controller = Controller.getInstance();
	@FXML
	private ComboBox<String> dialColorCB;
	@FXML
	private ComboBox<String> brandCB;
	@FXML
	private ComboBox<String> caseShapeCB;
	@FXML
	private ComboBox<String> caseMaterialCB;
	@FXML
	private TextField minPriceTF;
	@FXML
	private TextField maxPriceTF;
	@FXML
	private Label fullNameLabel;
	@FXML
	private Button logout;
	@FXML
	private Button deleteListingButton;
	@FXML
	private Label listingCount;
	@FXML
	private TextField referenceTF;

	// Event Listener on Button.onAction
	@FXML
	/**
	 * Clears all filters.
	 */
	public void clearFilters() {
		brandCB.getSelectionModel().clearSelection();
		caseShapeCB.getSelectionModel().clearSelection();
		caseMaterialCB.getSelectionModel().clearSelection();
		dialColorCB.getSelectionModel().clearSelection();
		minPriceTF.clear();
		maxPriceTF.clear();
	}
	// Event Listener on Button.onAction
	@FXML
	public void applyFilters() {
		String brand = brandCB.getSelectionModel().getSelectedItem();
		String shape= caseShapeCB.getSelectionModel().getSelectedItem();
		String material= caseMaterialCB.getSelectionModel().getSelectedItem();
		String color = dialColorCB.getSelectionModel().getSelectedItem();
		double minPrice = Double.parseDouble(minPriceTF.getText());
		double maxPrice = Double.parseDouble(minPriceTF.getText());
		//TODO sort by brand,shap,material,color,minPrice,maxPrice
	
	}
	// Event Listener on Label.onMouseClicked
	@FXML
	public void profileScene() {
		String email = controller.getCurrentUser().getEmail();
		ViewNavigator.loadScene(email.substring(0,email.indexOf('@')), ViewNavigator.ACCOUNT_OVERVIEW_SCENE);
	}
	// Event Listener on Label.onMouseClicked
	@FXML
	public void settingsScene(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void viewDetails(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void addToShoppingCart(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void addToWishlist(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void addListing(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteListingButton].onAction
	@FXML
	public void deleteListing(ActionEvent event) {
		// TODO Autogenerated
	}
}
