package edu.orangecoastcollege.watchplace.view;

import java.net.URL;
import java.util.ResourceBundle;

import edu.orangecoastcollege.watchplace.controller.Controller;
import edu.orangecoastcollege.watchplace.model.Watch;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
/**
 * 
 * @author Winston
 *
 */
public class HomeScene implements Initializable{ 
	private static Controller controller = Controller.getInstance();
	@FXML
	private ComboBox<String> dialColorCB;
	@FXML
	private ComboBox<String> brandCB;
	@FXML
	private ComboBox<String> caseShapeCB;
	@FXML
	private ComboBox<String> caseMaterialCB;
	@FXML
	private TextField minPriceTF;
	@FXML
	private TextField maxPriceTF;
	@FXML
	private Label fullNameLabel;
	@FXML
	private Button deleteListingButton;
	@FXML
	private Button viewDetailsButton;
	@FXML
	private Button addToShoppingCartButton;
	@FXML
	private Button addToWishListButton;
	@FXML
	private Label listingCount;
	@FXML
	private TextField referenceTF;
	@FXML
	private ListView<Watch> listView;
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		fullNameLabel.setText(controller.getCurrentUser().getName());
		listView.setItems(controller.getAllWatches());
		dialColorCB.setItems(controller.getDistinctDialColors());
		brandCB.setItems(controller.getDistinctBrands());
		caseShapeCB.setItems(controller.getDistinctCaseShape());
		caseMaterialCB.setItems(controller.getDistinctCaseMaterial());
		
		dialColorCB.setOnAction(e -> filter());
		brandCB.setOnAction(e -> filter());
		caseShapeCB.setOnAction(e -> filter());
		caseMaterialCB.setOnAction(e -> filter());
		minPriceTF.setOnAction(e -> filter());
		maxPriceTF.setOnAction(e -> filter());
	}
	
	private void filter() {
		String brand = brandCB.getSelectionModel().getSelectedItem();
		String shape = caseShapeCB.getSelectionModel().getSelectedItem();
		String material = caseMaterialCB.getSelectionModel().getSelectedItem();
		String color = dialColorCB.getSelectionModel().getSelectedItem();
		double minPrice = Double.parseDouble(minPriceTF.getText());
		double maxPrice = Double.parseDouble(minPriceTF.getText());
		
		listView.setItems(controller.filter(w -> (brand == null || w.getBrand().equalsIgnoreCase(brand))
				&& (shape == null || w.getCaseShape().equalsIgnoreCase(shape)) 
				&& (material == null || w.getCaseMaterial().equalsIgnoreCase(material))
				&& (color == null || w.getDialColor().equalsIgnoreCase(color))
				&& w.getPrice() >= minPrice
				&& w.getPrice() <= maxPrice));
	}
	@FXML
	public void logout()
	{
		controller.logoutUser();
	}
	// Event Listener on Button.onAction
	@FXML
	/**
	 * Clears all filters.
	 */
	public void clearFilters() {
		brandCB.getSelectionModel().clearSelection();
		caseShapeCB.getSelectionModel().clearSelection();
		caseMaterialCB.getSelectionModel().clearSelection();
		dialColorCB.getSelectionModel().clearSelection();
		minPriceTF.clear();
		maxPriceTF.clear();
	}

	// Event Listener on Button.onAction
	@FXML
	public void applyFilters() {
//		String brand = brandCB.getSelectionModel().getSelectedItem();
//		String shape = caseShapeCB.getSelectionModel().getSelectedItem();
//		String material = caseMaterialCB.getSelectionModel().getSelectedItem();
//		String color = dialColorCB.getSelectionModel().getSelectedItem();
//		double minPrice = Double.parseDouble(minPriceTF.getText());
//		double maxPrice = Double.parseDouble(minPriceTF.getText());
		filter();

	}

	// Event Listener on Label.onMouseClicked
	@FXML
	public void profileScene() {
		String email = controller.getCurrentUser().getEmail();
		ViewNavigator.loadScene(email.substring(0, email.indexOf('@')) + "'s Account",
				ViewNavigator.ACCOUNT_OVERVIEW_SCENE);
	}

	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToShoppingCart() {
		ViewNavigator.loadScene("Your Shopping Cart", ViewNavigator.SHOPPING_CART_SCENE);
	}

	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToWishList() {
		ViewNavigator.loadScene("Your Wish List", ViewNavigator.WISH_LIST_SCENE);
	}

	// Event Listener on Button.onAction
	@FXML
	public void viewDetails() {
		Watch itemName = listView.getSelectionModel().getSelectedItem();
		ViewNavigator.loadScene(itemName.getName(), ViewNavigator.VIEW_ITEM_DETAILS_SCENE);
	}

	// Event Listener on Button.onAction
	@FXML
	public void addToShoppingCart(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button.onAction
	@FXML
	public void addToWishlist(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button.onAction
	@FXML
	public void addListing() {
		ViewNavigator.loadScene("Add Listing", ViewNavigator.ADD_LISTING_SCENE);
	}

	// Event Listener on Button[#deleteListingButton].onAction
	@FXML
	public void deleteListing(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void checkSelected() {
		if(!listView.getSelectionModel().isEmpty())
		{
			deleteListingButton.setDisable(false);
			viewDetailsButton.setDisable(false);
			addToShoppingCartButton.setDisable(false);
			addToWishListButton.setDisable(false);
		}
	}
	
}
