package edu.orangecoastcollege.watchplace.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import edu.orangecoastcollege.watchplace.controller.Controller;
import javafx.event.ActionEvent;

import javafx.scene.control.Slider;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.input.MouseEvent;

public class HomeScene {
	
	private static Controller controller = Controller.getInstance();
	
	@FXML
	private ComboBox dialColorCB;
	@FXML
	private ComboBox brandCB;
	@FXML
	private ComboBox caseShapeCB;
	@FXML
	private ComboBox caseMaterialCB;
	@FXML
	private Slider minPriceSlider;
	@FXML
	private Slider maxPriceSlider;
	@FXML
	private Label fullNameLabel;
	@FXML
	private Button logout;

	// Event Listener on Button.onAction
	@FXML
	public void clearFilters(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void applyFilters(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label.onMouseClicked
	@FXML
	public void profileScene(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label.onMouseClicked
	@FXML
	public void settingsScene(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void viewDetails(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void addToShoppingCart(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void addToWishlist(ActionEvent event) {
		// TODO Autogenerated
	}
}
