package edu.orangecoastcollege.watchplace.view;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import edu.orangecoastcollege.watchplace.controller.Controller;
import edu.orangecoastcollege.watchplace.model.Review;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.ListView;

public class ProductReview implements Initializable{
	
	private static Controller controller = Controller.getInstance();
	@FXML
	private Label watchNameLabel;
	@FXML
	private Button addReviewButton;
	@FXML
	private Button viewButton;
	@FXML
	private Button goBackButton;
	
	private ListView<Review> reviewLV;

	// Event Listener on Button[#addReviewButton].onAction
	@FXML
	public void addReview(ActionEvent event) {
		ViewNavigator.loadScene("Add Review", ViewNavigator.ADD_WATCH_REVIEW_SCENE);
	}
	// Event Listener on Button[#viewButton].onAction
	@FXML
	public void viewReview(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#goBackButton].onAction
	@FXML
	public void goBack(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		//reviewLV.setItems(controller.getReviewsForWatch(controller.getSelectedListing().getWatch()));
		
	}
}
