package edu.orangecoastcollege.watchplace.view;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import edu.orangecoastcollege.watchplace.controller.Controller;
import edu.orangecoastcollege.watchplace.model.Review;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.ListView;

public class ProductReview implements Initializable{
	
	private static Controller controller = Controller.getInstance();
	@FXML
	private Label watchNameLabel;
	@FXML
	private Button addReviewButton;
	@FXML
	private Button viewButton;
	@FXML
	private Button goBackButton;
	
	private ListView<Review> reviewLV;
	
	/**
	 * Loads add review scene
	 */
	@FXML
	public void addReview() {
		ViewNavigator.loadScene("Add Review", ViewNavigator.ADD_WATCH_REVIEW_SCENE);
	}

	/**
	 * Loads the selected review
	 */
	@FXML
	public void viewReview() {
		// TODO Autogenerated
	}

	/**
	 * Goes back to the previous scene
	 */
	@FXML
	public void goBack() {
		// TODO Autogenerated
	}
	/**
	 * Initializes all nodes related to filtering and the ListView.
	 */
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		//reviewLV.setItems(controller.getReviewsForWatch());
		
	}
}
