package edu.orangecoastcollege.watchplace.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import edu.orangecoastcollege.watchplace.controller.Controller;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;

public class ShoppingCart {
	
	private static Controller controller = Controller.getInstance();
	
	@FXML
	private Label fullNameLabel;
	@FXML
	private ListView listView;
	@FXML
	private Button viewDetailsButton;
	@FXML
	private Button MoveToWishListButton;
	@FXML
	private Button deleteItemButton;
	@FXML
	private Label listingCount;

	// Event Listener on Label.onMouseClicked
	@FXML
	public void profileScene(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToCheckout(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void logout(ActionEvent event) {
		controller.logoutUser();
	}
	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToWishList(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToMain(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ListView[#listView].onMouseClicked
	@FXML
	public void checkSelected(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#viewDetailsButton].onAction
	@FXML
	public void viewDetails(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#MoveToWishListButton].onAction
	@FXML
	public void moveToWishlist(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteItemButton].onAction
	@FXML
	public void deleteItem(ActionEvent event) {
		// TODO Autogenerated
	}
}
