package edu.orangecoastcollege.watchplace.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import edu.orangecoastcollege.watchplace.controller.Controller;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;

public class ShoppingCart {
	
	private static Controller controller = Controller.getInstance();
	
	@FXML
	private Label fullNameLabel;
	@FXML
	private ListView listView;
	@FXML
	private Button viewDetailsButton;
	@FXML
	private Button addToWishListButton;
	@FXML
	private Button deleteItemButton;
	@FXML
	private Label cartItemCount;
	@FXML
	private Label ShoppingCartLabel;

	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToCheckout(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToMain(MouseEvent event) {
		ViewNavigator.loadScene("Welcome to WatchPlace", ViewNavigator.HOME_SCENE);
	}
	// Event Listener on Button.onAction
	@FXML
	public void logout(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToWishList(MouseEvent event) {
		ViewNavigator.loadScene("Your Wish List", ViewNavigator.WISH_LIST_SCENE);
	}
	// Event Listener on ListView[#listView].onMouseClicked
	@FXML
	public void checkSelected(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#viewDetailsButton].onAction
	@FXML
	public void viewDetails(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#addToWishListButton].onAction
	@FXML
	public void addToWishlist(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteItemButton].onAction
	@FXML
	public void deleteListing(ActionEvent event) {
		// TODO Autogenerated
	}
}
