package edu.orangecoastcollege.watchplace.view;

import java.net.URL;
import java.util.ResourceBundle;

import edu.orangecoastcollege.watchplace.controller.Controller;
import edu.orangecoastcollege.watchplace.model.Listing;
import edu.orangecoastcollege.watchplace.model.Watch;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.input.MouseEvent;

public class Wishlist implements Initializable {
	
	private static Controller controller = Controller.getInstance();
	
	@FXML
	private Label fullNameLabel;
	@FXML
	private ListView<Watch> listView;
	@FXML
	private Button viewDetailsButton;
	@FXML
	private Button addToShoppingCartButton;
	@FXML
	private Button deleteItemButton;
	@FXML
	private Label cartItemCount;
	@FXML
	private Label ShoppingCartLabel;
	
	/*public void initialize(URL location, ResourceBundle resources) {
	    listView.setItems(controller.getWatchesForCurrentUser());
	    fullNameLabel.setText(controller.getCurrentUser().getName());
	}*/
	
	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToCheckout(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToMain(MouseEvent event) {
		ViewNavigator.loadScene("Welcome to WatchPlace", ViewNavigator.HOME_SCENE);
	}
	// Event Listener on Button.onAction
	@FXML
	public void logout(ActionEvent event) {
		controller.logoutUser();
	}
	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToShoppingCart(MouseEvent event) {
		ViewNavigator.loadScene("Your Shopping Cart", ViewNavigator.SHOPPING_CART_SCENE);
	}
	// Event Listener on ListView[#listView].onMouseClicked
	@FXML
	public void checkSelected() {
		if(!listView.getSelectionModel().isEmpty())
		{
			deleteItemButton.setDisable(false);
			addToShoppingCartButton.setDisable(false);
		}
		else
		{
			deleteItemButton.setDisable(true);
			addToShoppingCartButton.setDisable(true);
		}
	}
	
	@FXML
	public void addToShoppingCart(ActionEvent event) {
		
		Watch w = listView.getSelectionModel().getSelectedItem();
		boolean add = controller.addWatchToShoppingCart(w);
		controller.deleteWishlistItem(w.getId());
		listView.setItems(controller.getWishlistWatchesForCurrentUser());
		listView.getSelectionModel().select(-1);
		checkSelected();
	}
	
	@FXML
	public void deleteItem(ActionEvent event) {
		controller.deleteWishlistItem(((Watch) listView.getSelectionModel().getSelectedItem()).getId());
		listView.setItems(controller.getWishlistWatchesForCurrentUser());
		
	}
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		
		listView.setItems(controller.getWishlistWatchesForCurrentUser());
		fullNameLabel.setText(controller.getCurrentUser().getName());
		
		deleteItemButton.setOnAction(e -> deleteItem(e));
		
	}
}
