package edu.orangecoastcollege.watchplace.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;

public class WIshlist {
	@FXML
	private Label fullNameLabel;
	@FXML
	private ListView listView;
	@FXML
	private Button viewDetailsButton;
	@FXML
	private Button addToWishListButton;
	@FXML
	private Button deleteItemButton;
	@FXML
	private Label cartItemCount;
	@FXML
	private Label ShoppingCartLabel;

	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToCheckout(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToMain(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void logout(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label.onMouseClicked
	@FXML
	public void goToShoppingCart(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ListView[#listView].onMouseClicked
	@FXML
	public void checkSelected(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#viewDetailsButton].onAction
	@FXML
	public void viewDetails(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#addToWishListButton].onAction
	@FXML
	public void addToWishlist(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteItemButton].onAction
	@FXML
	public void deleteListing(ActionEvent event) {
		// TODO Autogenerated
	}
}
